<?xml version="1.0" encoding="utf-8"?><Database Name="EquipmentLogs" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CNS-VM-SQL08R2;Initial Catalog=EquipmentLogs;Persist Security Info=True;User ID=SA" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="EquipmentLogsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Equipment" Member="Equipments">
    <Type Name="Equipment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagID" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SerialNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BitlockerStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DateEncryptionChecked" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CurrentLocation" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PreviousLocation" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CurrentAssignee" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PreviousAssignee" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Destroyed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsPatient" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Installed Software]" Member="Installed_Software" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[P Software]" Member="P_Software" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>