<?xml version="1.0" encoding="utf-8"?><Database Name="ITTickets" Class="TicketsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.10.23;Initial Catalog=ITTickets;Persist Security Info=True;User ID=Sa" SettingsObjectName="CNS_Access_List.Properties.Settings" SettingsPropertyName="ITTicketsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ticketer" Member="Ticketers">
    <Type Name="Ticketer">
      <Column Name="Ticketor" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Tphone" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Temail" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Dissue" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Issue" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Resolver" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Remail" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Rphone" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Resolution" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ID2" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Dresolve" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DeviceID" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IssueType" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Priority" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Supported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Assigned" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>