<?xml version="1.0" encoding="utf-8"?><Database Name="EquipmentLogs" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CNS-VM-SQL08R2;Initial Catalog=EquipmentLogs;Persist Security Info=True;User ID=SA" SettingsObjectName="CNS_Access_List.Properties.Settings" SettingsPropertyName="EquipmentLogsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[First name]" Member="First_name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Last name]" Member="Last_name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Username" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Location" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Department" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BatFile" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Security" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Drives" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Async" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IncomingEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OutgoingEmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserHistory" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>