#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNS_Access_List.Data_Connections
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EquipmentLogs")]
	public partial class UsersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public UsersDataContext() : 
				base(global::CNS_Access_List.Properties.Settings.Default.EquipmentLogsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _First_name;
		
		private string _Last_name;
		
		private string _Username;
		
		private string _Location;
		
		private string _Department;
		
		private System.Nullable<char> _Status;
		
		private string _BatFile;
		
		private string _Security;
		
		private string _Drives;
		
		private System.Nullable<bool> _Async;
		
		private System.Nullable<bool> _IncomingEmail;
		
		private System.Nullable<bool> _OutgoingEmail;
		
		private string _UserHistory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnLast_nameChanging(string value);
    partial void OnLast_nameChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnStatusChanging(System.Nullable<char> value);
    partial void OnStatusChanged();
    partial void OnBatFileChanging(string value);
    partial void OnBatFileChanged();
    partial void OnSecurityChanging(string value);
    partial void OnSecurityChanged();
    partial void OnDrivesChanging(string value);
    partial void OnDrivesChanged();
    partial void OnAsyncChanging(System.Nullable<bool> value);
    partial void OnAsyncChanged();
    partial void OnIncomingEmailChanging(System.Nullable<bool> value);
    partial void OnIncomingEmailChanged();
    partial void OnOutgoingEmailChanging(System.Nullable<bool> value);
    partial void OnOutgoingEmailChanged();
    partial void OnUserHistoryChanging(string value);
    partial void OnUserHistoryChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First name]", Storage="_First_name", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string First_name
		{
			get
			{
				return this._First_name;
			}
			set
			{
				if ((this._First_name != value))
				{
					this.OnFirst_nameChanging(value);
					this.SendPropertyChanging();
					this._First_name = value;
					this.SendPropertyChanged("First_name");
					this.OnFirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last name]", Storage="_Last_name", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Last_name
		{
			get
			{
				return this._Last_name;
			}
			set
			{
				if ((this._Last_name != value))
				{
					this.OnLast_nameChanging(value);
					this.SendPropertyChanging();
					this._Last_name = value;
					this.SendPropertyChanged("Last_name");
					this.OnLast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
		public System.Nullable<char> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatFile", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BatFile
		{
			get
			{
				return this._BatFile;
			}
			set
			{
				if ((this._BatFile != value))
				{
					this.OnBatFileChanging(value);
					this.SendPropertyChanging();
					this._BatFile = value;
					this.SendPropertyChanged("BatFile");
					this.OnBatFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Security", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Security
		{
			get
			{
				return this._Security;
			}
			set
			{
				if ((this._Security != value))
				{
					this.OnSecurityChanging(value);
					this.SendPropertyChanging();
					this._Security = value;
					this.SendPropertyChanged("Security");
					this.OnSecurityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Drives", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Drives
		{
			get
			{
				return this._Drives;
			}
			set
			{
				if ((this._Drives != value))
				{
					this.OnDrivesChanging(value);
					this.SendPropertyChanging();
					this._Drives = value;
					this.SendPropertyChanged("Drives");
					this.OnDrivesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Async", DbType="Bit")]
		public System.Nullable<bool> Async
		{
			get
			{
				return this._Async;
			}
			set
			{
				if ((this._Async != value))
				{
					this.OnAsyncChanging(value);
					this.SendPropertyChanging();
					this._Async = value;
					this.SendPropertyChanged("Async");
					this.OnAsyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncomingEmail", DbType="Bit")]
		public System.Nullable<bool> IncomingEmail
		{
			get
			{
				return this._IncomingEmail;
			}
			set
			{
				if ((this._IncomingEmail != value))
				{
					this.OnIncomingEmailChanging(value);
					this.SendPropertyChanging();
					this._IncomingEmail = value;
					this.SendPropertyChanged("IncomingEmail");
					this.OnIncomingEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutgoingEmail", DbType="Bit")]
		public System.Nullable<bool> OutgoingEmail
		{
			get
			{
				return this._OutgoingEmail;
			}
			set
			{
				if ((this._OutgoingEmail != value))
				{
					this.OnOutgoingEmailChanging(value);
					this.SendPropertyChanging();
					this._OutgoingEmail = value;
					this.SendPropertyChanged("OutgoingEmail");
					this.OnOutgoingEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserHistory", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string UserHistory
		{
			get
			{
				return this._UserHistory;
			}
			set
			{
				if ((this._UserHistory != value))
				{
					this.OnUserHistoryChanging(value);
					this.SendPropertyChanging();
					this._UserHistory = value;
					this.SendPropertyChanged("UserHistory");
					this.OnUserHistoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
